### ISSUE TITLE
The user shouldn't have to input IDs everywhere to handle lists and recipes

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-Diasks#1]
@Diasks your application works just fine if the user knows their own user id and the id of the list they created but, there isn't really a recipe application that works like this. So, I'm going to have to ask you to handle this in your frontend.

*To be crystal clear*:

- [x] The user should be able to add/remove recipes from list(s) without inputting a) their unique id or b) the unique id of a list

- [x] The user should also be able to edit/update the information on lists without inputting a) the id of the list

- [x] The user should be able to add more than one recipe to a list

- [x] The user should also be able to view the recipe(s) that's added to any list just like they can when they search for them

**Comment by Diasks** [comment]
@axelolsson I have fixed everything you mentioned, it's deployed and ready for a try!

**Comment by axeberg** [comment]
@Diasks awesome, I did find a little bug though. I can add the same recipe to a list several times. Even if it already exists in the list!

**Comment by axeberg** [comment]
Minor issue in the grand scheme of things so wont require a fix for this. Well done!
